### ISSUE TITLE
Batch images on Windows

### ISSUE THREAD

**Issue by herrartist** [Limbicnation/TransformDepth#1]
How can I batch images on Windows? The image path thing doesn't work with an Anaconda powershell prompt.

**Comment by Limbicnation** [comment]
@herrartist  Please update and review this section for batch image processing:  https://github.com/Limbicnation/TransformDepth/tree/main?tab=readme-ov-file#run-the-script-for-batchsingle-image-processing-with-a-specified-output-directory-

Also, make sure to created the virtual environment with Anaconda as stated in the [readme](https://github.com/Limbicnation/TransformDepth/tree/main?tab=readme-ov-file#environment-setup-) and install the ```requirements.txt``` with ```pip install -r requirements.txt```
