### ISSUE TITLE
Batch not running

### ISSUE THREAD

**Issue by herrartist** [Limbicnation/TransformDepth#4]
When I do the input:

python DepthEstimationPipeline.py --batch .. \Users\mail\Desktop\TransformDepth-main\input --output \Users\mail\Desktop\TransformDepth-main\output .. \images\batch

I get an error message
Syntax error: invalid syntax
File "DepthEstimationPipeline.py", line 27
depth_image.save(C:Users\mail\Desktop\TransformDepth-main\output)

Can you please write a tutorial for non-programmers how to start the batch process?

**Comment by Limbicnation** [comment]
> When I do the input:
> 
> python DepthEstimationPipeline.py --batch .. \Users\mail\Desktop\TransformDepth-main\input --output \Users\mail\Desktop\TransformDepth-main\output .. \images\batch
> 
> I get an error message Syntax error: invalid syntax File "DepthEstimationPipeline.py", line 27 depth_image.save(C:Users\mail\Desktop\TransformDepth-main\output)
> 
> Can you please write a tutorial for non-programmers how to start the batch process?

@herrartist Thank you for your interest in the TransformDepth repo. I have recently made an update and also provided a [tutorial](https://www.youtube.com/watch?v=sMi2nBE2nT0&t=45s). I hope this helps! 

Please use `git pull` to get the latest changes.
